[pytest]
testpaths = tests
python_files = test_*
python_classes = *Test
python_functions = test_*
log_cli = true
log_level = INFO
markers=
        smoke
        validation
        ui_ux
        account_creation
        security
        performance
        accessibility
        regression
        acceptance
        integration
        unit
        integration

;addopts = --template=html1/index.html --report=report.html
addopts = -v -n auto --junitxml="result.xml" --html=report.html --self-contained-html --log-format='%(asctime)s [%(levelname)s] [%(name)s] %(message)s' --reruns 2 --alluredir=allure-report

# Console output configuration
console_output_style = progress